### ISSUE TITLE
Syncing stops at 21 February at 21:15. Also after delete app and Reinstall app.

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#123] opened 2018-02-25 12:04 UTC
**What happened:**
```
Syncing stops at 21 February at 21:15. Also after delete app and Reinstall app.
```

**Version:** 2.0.0 (1274)

**Operating system:** iOS 11.2.2

**Model:** iPhone 6S

**Memory:** 98% (1.24 GB used out of 1.26 GB)

**Capacity:** 70% (21 GB used out of 29.8 GB)

**Locale:** Netherlands Dutch; Flemish

**Network:** vf nl LTE (4G)

**WiFi:** Disconnected

**Attachments:** 

![IMG_1309.PNG](http://buglife.s3.amazonaws.com/report_attachments/c94ae771896206d21bd95db2fd330eec4a5f2544/original/IMG_1309.PNG?1519560290)

**URL:** http://buglife.com/apps/breadwallet/reports/92

Reported via Buglife

**Comment by ChillingSilence** [comment] 2018-02-26 02:45
Duplicate of #121

**Closed** 2018-02-26 02:45 UTC
